# Generated by Django 4.2.6 on 2023-10-20 21:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
                ('alt_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('seal_date', models.DateField(blank=True, null=True)),
                ('seal_square_footage', models.IntegerField()),
                ('seal_quote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patch_date', models.DateField(blank=True, null=True)),
                ('patch_square_footage', models.IntegerField(blank=True, null=True)),
                ('patch_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caulk_date', models.DateField(blank=True, null=True)),
                ('caulk_square_footage', models.IntegerField(blank=True, null=True)),
                ('caulk_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_front.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_field', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_front.propertymodel')),
            ],
        ),
    ]
