# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memomodel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='web_front.propertymodel'),
        ),
    ]
