# Generated by Django 4.2.6 on 2023-11-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0002_alter_memomodel_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='caulk_date',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='caulk_quote',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='caulk_square_footage',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='patch_date',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='patch_quote',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='seal_date',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='seal_quote',
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seal_date', models.DateField(blank=True, null=True)),
                ('job_seal_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('job_patch_date', models.DateField(blank=True, null=True)),
                ('job_patch_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('job_caulk_date', models.DateField(blank=True, null=True)),
                ('job_caulk_footage', models.IntegerField(blank=True, null=True)),
                ('job_notes', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='web_front.propertymodel')),
            ],
        ),
    ]
