# Generated by Django 4.2.6 on 2023-11-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0003_remove_propertymodel_caulk_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_seal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_seal_square_footage', models.IntegerField(blank=True, null=True)),
                ('seal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('patch_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='patch_square_footage',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_patch_square_footage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_total_quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='web_front.jobmodel')),
            ],
        ),
    ]
