# Generated by Django 4.2.6 on 2023-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0004_constantsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constantsmodel',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
