# Generated by Django 4.2.6 on 2023-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_front', '0005_remove_constantsmodel_tax_rate_jobmodel_job_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_seal_square_footage',
            field=models.IntegerField(default=0),
        ),
    ]
