# Generated by Django 4.2.6 on 2023-11-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_front", "0006_jobmodel_job_seal_square_footage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="created_by",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customermodel",
            name="updated_by",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
