# Generated by Django 4.2.6 on 2023-11-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_front", "0008_leadsmodel_remediationneededmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsmodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="remediationneededmodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="remediationneededmodel",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="remediationneededmodel",
            name="last_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
