# Generated by Django 4.2.6 on 2023-11-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_front", "0009_alter_leadsmodel_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remediationneededmodel",
            name="alt_phone_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remediationneededmodel",
            name="phone_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
